spring.application.name=SpringBoot2026-DEV

# Configurazione Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/academy_ecommerce
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA / Hibernate
# Nota: hibernate.dialect rimosso (rilevato automaticamente)
spring.jpa.show-sql=true
# Forza l'uso esclusivo di Liquibase per la struttura del DB
spring.jpa.hibernate.ddl-auto=none
# Disabilita Open-In-View per performance e pulizia log
spring.jpa.open-in-view=false

# Configurazione Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=academy_ecommerce

# Livelli di Log ottimizzati
logging.level.org.springframework.boot.autoconfigure.liquibase=INFO
logging.level.liquibase=INFO

# Configurazione JWT
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.ms=86400000

# Configurazione Stripe
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=http://localhost:8080/api/order/success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel.url=http://localhost:8080/api/order/cancel
