databaseChangeLog:
  - changeSet:
      id: create-table-product
      author: academy2026
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: BINARY(16)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(100)
                  constraints:
                    nullable: false
              - column:
                  name: category_id
                  type: BINARY(16)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: DECIMAL(10, 2)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT

# Aggiunto campo stock per la disponibilità di un articolo
  - changeSet:
      id: 20260418174743
      author: dicorradoalex
      changes:
        - addColumn:
            tableName: product
            columns:
              - column:
                  name: stock
                  type: INT
                  defaultValueNumeric: 0
                  constraints:
                    nullable: false

# Aggiunto campo per soft delete
  - changeSet:
      id: 20260423101206
      author: dicorradoalex
      changes:
        - addColumn:
            tableName: product
            columns:
              - column:
                  name: deleted
                  type: boolean
                  defaultValueBoolean: false
                  constraints:
                    nullable: false